<!DOCTYPE html>
<html lang="en-US">
<head>
    <?= $this->meta->head($post); ?>
    <script>POST={id:<?= $post->id ?>,stat:"<?= $this->router->to('sitePostStatistic') ?>"}</script>
</head>
<body>
    
    <h1><?= $post->title ?></h1>
    <time><?= $post->created->format('M d, Y') ?></time>
    
    <article data-post="content"><?= $post->content ?></article>
    
    <p>By: <?= $post->user->fullname ?></p>
    
    <ul>
    <?php if(isset($post->category)): ?>
        <li>
            <span>Categories</span>
            <ul>
                <?php foreach($post->category as $cat): ?>
                <li><a href="<?= $cat->page ?>"><?= $cat->name ?></a></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if(isset($post->tag)): ?>
        <li>
            <span>Tags</span>
            <ul>
                <?php foreach($post->tag as $tag): ?>
                <li><a href="<?= $tag->page ?>"><?= $tag->name ?></a></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if($post->canal): ?>
        <li>
            Canal: <a href="<?= $post->canal->page ?>"><?= $post->canal->name ?></a>
        </li>
    <?php endif; ?>
    </ul>
    
    <?php if($pagination): ?>
        <ul>
            <?php foreach($pagination as $label => $link): ?>
            <li><a href="<?= $link ?>"><?= $label ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
    <?= $this->meta->foot($post); ?>
    
    <script src="<?= $this->asset('js/post.min.js'); ?>"></script>
</body>
</html>